// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BioFSharp.Mz")>]
[<assembly: AssemblyProductAttribute("BioFSharp.Mz")>]
[<assembly: AssemblyDescriptionAttribute("BioFSharp.Mz - modular computational proteomics")>]
[<assembly: AssemblyVersionAttribute("0.0.111")>]
[<assembly: AssemblyFileVersionAttribute("0.0.111")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BioFSharp.Mz"
    let [<Literal>] AssemblyProduct = "BioFSharp.Mz"
    let [<Literal>] AssemblyDescription = "BioFSharp.Mz - modular computational proteomics"
    let [<Literal>] AssemblyVersion = "0.0.111"
    let [<Literal>] AssemblyFileVersion = "0.0.111"
    let [<Literal>] AssemblyConfiguration = "Release"
