name: deploy-gh-pages

on:
  push:
    branches: [ developer ]

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore
      run: dotnet restore
    - name: Build
      working-directory: ./
      run: dotnet fsdocs build --eval --noapidocs
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./output # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
